#+Title: Aner's Emacs Configuration
#+property: header-args :results silent
#+LATEX_HEADER: \usepackage{xcolor}
#+LATEX_HEADER: \usepackage{minted}
#+LATEX_HEADER: \usepackage{polyglossia}
#+LATEX_HEADER: \setotherlanguage{hebrew}
#+LATEX_HEADER: \newfontfamily\hebrewfont{Noto Sans Hebrew}[Script=Hebrew]
#+begin_export latex
\definecolor{codebg}{rgb}{0.95,0.95,0.95}
\setminted{
  bgcolor=codebg,
  breaklines=true,
  mathescape,
  linenos=false,
  fontsize=\scriptsize
}
#+end_export

* Base Configuration
  

** Package installation

Installation of all required packages.

Taken from [[https://stackoverflow.com/questions/55038594/setting-up-emacs-on-new-machine-with-init-el-and-package-installation ][this post on StackOverflow]].

Declare repositories:

#+begin_src emacs-lisp :latex_attr optoins bgcolor=dark
(setq package-archives
      '(("gnu" . "http://elpa.gnu.org/packages/")
        ("melpa" . "http://melpa.org/packages/")))
#+end_src

Initialize package management and refresh repositories unless archived.
If repositories need to be refreshed, this command should be called.

#+begin_src emacs-lisp
(require 'package)
(package-initialize)

(unless package-archive-contents
  (package-refresh-contents))
#+end_src

Defining a function to install a package unless already installed
#+begin_src emacs-lisp
(defun package-unless-install(pkg)
  (unless (package-installed-p pkg)
    (package-install pkg)))
#+end_src

** Backup files

Taken from [[https://stackoverflow.com/questions/151945/how-do-i-control-how-emacs-makes-backup-files][this post on StackOverflow]]

#+begin_src emacs-lisp
(setq backup-directory-alist `(("." . "~/.cache/emacs-backups/")))
(setq backup-by-copying t)
(setq delete-old-versions t
  kept-new-versions 6
  kept-old-versions 2
   version-control t)
#+end_src

* UI

** Clean UI
Disabling the toolbar, the splash-screen, the menu-bar and the scroll-bar
#+begin_src emacs-lisp
(customize-set-variable 'inhibit-startup-screen t) ; no splash screen on start
(tool-bar-mode -1)   ; no tool bar with icons
(scroll-bar-mode -1) ; no scroll bars
(menu-bar-mode -1)   ; no menu bar
#+end_src

** Window dividers
Customizing space between windows
#+begin_src emacs-lisp
(window-divider-mode 0)
(set-face-foreground 'vertical-border "LightGray")
(set-face-background 'fringe "WhiteSmoke")
;For theme-independent configuration
;(set-face-foreground 'vertical-border (face-attribute 'mode-line :background))
;(set-face-background 'fringe (face-attribute 'mode-line-inactive :background))
#+end_src

** Text

*** Text format
Setting font size to 10. The value to place is font-size * 10

#+begin_src emacs-lisp
(set-face-attribute 'default nil :height 100)
#+end_src

*** Line numbering
#+begin_src emacs-lisp
(setq display-line-numbers-type 'visual)
(setq display-line-numbers-grow-only 1)
(setq display-line-numbers-width-start 1)
(when (version<= "26.0.50" emacs-version )
(global-display-line-numbers-mode))
#+end_src

*** Line highlight
#+begin_src emacs-lisp
(global-hl-line-mode)
#+end_src

*** Line wrap
 #+begin_src emacs-lisp
(global-visual-line-mode t)
 #+end_src

*** Parenthesis
Highlight matching parenthesis
 #+begin_src emacs-lisp
(show-paren-mode 1)
 #+end_src

*** Tabs
#+begin_src emacs-lisp
(setq-default indent-tabs-mode nil)
(setq default-tab-width 4)
#+end_src

** Modeline

#+begin_src emacs-lisp
;(package-unless-install 'smart-mode-line)
;(setq sml/no-confirm-load-theme t)
;(sml/setup)
;(setq sml/theme 'light)
#+end_src

** Which-Key

#+begin_src emacs-lisp
(package-unless-install 'which-key)
(require 'which-key)
(which-key-mode)
#+end_src

** Perspective

#+begin_src emacs-lisp
(package-unless-install 'perspective)
(require 'perspective)
(persp-mode 1)
#+end_src

*** Keymaps

#+begin_src emacs-lisp
(eval-after-load "org"
    '(define-key org-mode-map (kbd "M-<tab>") nil))
;Unset org-mode map "org-force-cycle-archived"
(global-set-key (kbd "M-<tab>") 'persp-next)
(global-set-key (kbd "M-`") 'persp-prev)
(global-set-key (kbd "M-n") 'persp-switch)
#+end_src

** Active Window Background

#+begin_src emacs-lisp
(defun highlight-selected-window ()
    ;Walk through all buffers, set all other buffers to
    ;default background
    (walk-windows (lambda (w)
    (with-current-buffer (window-buffer w)
        (unless (eq w (selected-window))
        (progn
            (buffer-face-set 'default)
            ;(face-remap-remove-relative fringeface)
                )
        )
    )
    ))
    ;Finally, set current buffer background
    (buffer-face-set '(:background "PaleTurquoise1"))
    (if (minibuffer-window-active-p (selected-window))
        (buffer-face-set '(:background "PaleTurquoise1"))
        (buffer-face-set '(:background "LightYellow"))
    )
)
;(add-hook 'buffer-list-update-hook 'highlight-selected-window)
(add-hook 'post-command-hook 'highlight-selected-window)
#+end_src

** Easy Prompt

#+begin_src emacs-lisp
(defalias 'yes-or-no-p 'y-or-n-p)
#+end_src

** General Keymaps

 Window splitting:
 #+begin_src emacs-lisp
;;Instead of delete-horizontal-space
(global-set-key (kbd "M-\\") 'split-window-horizontally)
;;Instead of negative-argument
(global-set-key (kbd "M-\-") 'split-window-vertically)
 #+end_src

 Window movement:
#+begin_src emacs-lisp
;;Unset the org-mode map of "org-mark-element"
(eval-after-load "org"
    '(define-key org-mode-map (kbd "M-h") nil)) 

;;Instead of mark-paragraph (and org mark element)
(global-set-key (kbd "M-h") 'windmove-left)

;;Instead of downcase-word
(global-set-key (kbd "M-l") 'windmove-right) 
;;Instead of kill-sentence
(global-set-key (kbd "M-k") 'windmove-up) 
;;Instead of indent-new-comment-line
(global-set-key (kbd "M-j") 'windmove-down)
;;Instead of mark-paragraph
(global-set-key (kbd "M-<left>") 'windmove-left)
;;Instead of downcase-word
(global-set-key (kbd "M-<rijjt>") 'windmove-right)
;;Instead of kill-sentence
(global-set-key (kbd "M-<up>") 'windmove-up)
;;Instead of indent-new-comment-line
(global-set-key (kbd "M-<down>") 'windmove-down)
(global-unset-key (kbd "M-d")) ;;Instead of kill-word
;;Instead of indent-new-comment-line
(global-set-key (kbd "M-d M-d") 'delete-window)
;;Instead of indent-new-comment-line
(global-set-key (kbd "M-d D") 'kill-buffer-and-window)
(defun set-window-width (n)
    (adjust-window-trailing-edge (selected-window) ( - n (window-width)) t))
(defun set-85-columns()
    (interactive)
    (set-window-width 85))
;;Instead of indent-new-comment-line
(global-set-key (kbd "M-d R") 'set-85-columns)
#+end_src

Buffers:
#+begin_src emacs-lisp
;(eval-after-load "evil-autoloads"
;    '(define-key evil-normal-state-map (kbd "C-b") nil))
;(eval-after-load "evil-autoloads"
;    '(global-set-key (kbd "C-b C-b") 'buffer-menu))
;(eval-after-load "evil-autoloads"
;    '(global-set-key (kbd "C-b C-d") 'kill-buffer))
#+end_src

** Centaur tabs

#+begin_src emacs-lisp
;(package-unless-install 'centaur-tabs)
;(centaur-tabs-mode t)
;(global-set-key (kbd "C-<prior>")  'centaur-tabs-backward)
;(global-set-key (kbd "C-<next>") 'centaur-tabs-forward)
;(centaur-tabs-mode t)
#+end_src

* Global modes
  
** EVIL mode

#+begin_src emacs-lisp
(package-unless-install 'evil)
(require 'evil )
(evil-mode 1)
#+end_src

** IVY

Enabling IVY. Taken from [[https://github.com/abo-abo/swiper][their website]].

#+begin_src emacs-lisp
(package-unless-install 'ivy)
(require 'ivy)
(package-unless-install 'ivy-hydra)
(require 'ivy-hydra)
(ivy-mode 1)
(setq ivy-use-virtual-buffers t)
(setq enable-recursive-minibuffers t)
(setq ivy-count-format "(%d/%d) ")
#+end_src

*** Keymaps

#+begin_src emacs-lisp
(define-key ivy-minibuffer-map (kbd "C-j") 'ivy-next-line)
(define-key ivy-minibuffer-map (kbd "C-k") 'ivy-previous-line)
#+end_src

** Projectile

Package installation
#+begin_src emacs-lisp
(package-unless-install 'projectile)
(projectile-mode +1)
(define-key projectile-mode-map (kbd "M-p") 'projectile-command-map)
(define-key projectile-mode-map (kbd "M-p a") 'projectile-add-known-project)
#+end_src

Ivy for projectile:
#+begin_src emacs-lisp
(package-unless-install 'counsel-projectile)
(require 'counsel-projectile)
(counsel-projectile-mode +1)
#+end_src

Fixing counsel to display keymaps during M-x
Taken from [[https://emacs.stackexchange.com/questions/40787/display-corresponding-key-binding-of-command-during-m-x-completion][this post]] and [[https://emacs.stackexchange.com/questions/38841/counsel-m-x-always-shows][this post]] from StackOverflow.

#+begin_src emacs-lisp
(when (commandp 'counsel-M-x)
    (global-set-key [remap execute-extended-command] 'counsel-M-x))
(setcdr (assoc 'counsel-M-x ivy-initial-inputs-alist) "")
#+end_src

#+begin_src emacs-lisp
;(centaur-tabs-group-by-projectile-project)
#+end_src

*** Keymaps

#+begin_src emacs-lisp
(global-set-key (kbd "C-b") 'projectile-display-buffer)
#+end_src

* Major modes

** Multi-Term

#+begin_src emacs-lisp
(require 'multi-term)
#+end_src

** PDF-Tools

For viewing PDF files and such! YAY
#+begin_src emacs-lisp
;(package-unless-install 'pdf-tools)
;(require 'pdf-tools)
;(pdf-tools-install)
#+end_src

*** Stop the blinking

Taken from [[https://github.com/munen/emacs.d/blob/master/configuration.org][Munen's configuration on GitHub]].
When using evil-mode and pdf-tools and looking at a zoomed PDF, it will blink, because the cursor blinks.
This configuration disables this whilst retaining the blinking cursor in other modes.
#+begin_src emacs-lisp
(evil-set-initial-state 'pdf-view-mode 'emacs)
(add-hook 'pdf-view-mode-hook
  (lambda ()
    (set (make-local-variable 'evil-emacs-state-cursor) (list nil))))
#+end_src

** ORG
   
*** General
*** Babel

Define languages to use 

#+begin_src emacs-lisp
(require 'ob)
(require 'ob-tangle)

(org-babel-do-load-languages
 'org-babel-load-languages
 '((shell . t)
   (emacs-lisp . t)
   (python . t)
   (org . t)
   (lilypond . t)
   (latex . t)
   (js . t)
   (java . t)
   (C . t)))

(add-to-list 'org-src-lang-modes (quote ("dot". graphviz-dot)))
(add-to-list 'org-src-lang-modes (quote ("plantuml" . fundamental)))
(add-to-list 'org-babel-tangle-lang-exts '("clojure" . "clj"))
#+end_src

*** Code blocks

The following displays the contents of code blocks in Org-mode files using
the major-mode of the code. It also changes the behavior of TAB to as if it
were used in the appropriate major mode.

#+begin_src emacs-lisp
(setq org-src-fontify-natively t)
(setq org-src-tab-acts-natively t)
(setq org-src-preserve-indentation 1)
#+end_src

*** HTML Preview

#+begin_src emacs-lisp
(package-unless-install 'org-preview-html)
(package-unless-install 'htmlize)
(require 'org-preview-html)
(require 'htmlize)
#+end_src

*** PDF Preview

#+begin_src emacs-lisp
(package-unless-install 'latex-preview-pane)
#+end_src

*** Minted
    
#+begin_src emacs-lisp
(setq org-latex-listings 'minted)
(setq org-latex-packages-alist '(("" "minted" "xcolor" "polyglossia")))
(setq org-latex-pdf-process
      '("xelatex -shell-escape -interaction nonstopmode -output-directory %o %f"))
#+end_src

*** Fixing previews for things with polygloss
#+begin_src emacs-lisp
;(setq org-preview-latex-process-alist '(())
#+end_src

This should render Hebrew text.

#+begin_export latex
\begin{hebrew}
#+end_export

זה אמור לעבוד

#+begin_export latex
\end{hebrew}
#+end_export

*** Org block highlighting
#+begin_src emacs-lisp
(set-face-background 'org-block-begin-line "gray")
(set-face-background 'org-block "white")
(set-face-background 'org-block-end-line "gray")
#+end_src
*** Useful to remember

To preview latex fragment as image embedded in text
#+begin_example
org-toggle-latex-fragment
#+end_example

** Markdown

#+begin_src emacs-lisp
(package-unless-install 'markdown-mode)
(require 'markdown-mode)
#+end_src

