# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="/home/aner/.oh-my-zsh"

# Uncomment the following line to use hyphen-insensitive completion.
# Case-sensitive completion must be off. _ and - will be interchangeable.
# HYPHEN_INSENSITIVE="true"

# Uncomment the following line to disable bi-weekly auto-update checks.
# DISABLE_AUTO_UPDATE="true"

# Uncomment the following line to automatically update without prompting.
# DISABLE_UPDATE_PROMPT="true"

# Uncomment the following line to change how often to auto-update (in days).
# export UPDATE_ZSH_DAYS=13

# Uncomment the following line if pasting URLs and other text is messed up.
# DISABLE_MAGIC_FUNCTIONS=true

# Uncomment the following line to disable colors in ls.
# DISABLE_LS_COLORS="true"

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

# Uncomment the following line to display red dots whilst waiting for completion.
# COMPLETION_WAITING_DOTS="true"

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Uncomment the following line if you want to change the command execution time
# stamp shown in the history command output.
# You can set one of the optional three formats:
# "mm/dd/yyyy"|"dd.mm.yyyy"|"yyyy-mm-dd"
# or set a custom format using the strftime function format specifications,
# see 'man strftime' for details.
# HIST_STAMPS="mm/dd/yyyy"

# Would you like to use another custom folder than $ZSH/custom?
# ZSH_CUSTOM=/path/to/new-custom-folder

export FZF_BASE=~/.fzf

# Which plugins would you like to load?
# Standard plugins can be found in ~/.oh-my-zsh/plugins/*
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
# Add wisely, as too many plugins slow down shell startup.
plugins=(git-prompt vi-mode colored-man-pages fzf zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh

#Setting PS1
#PS1_command_stripped=$(sed "s,\x1B\[[0-9;]*[a-zA-Z],,g" <<<"$PS1_command")

ZSH_THEME_GIT_PROMPT_BRANCH="%{$fg[blue]%}"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8
 
export EDITOR='vim'

autoload edit-command-line; zle -N edit-command-line
bindkey '^e' edit-command-line

PS1=$'%{\e[0m%}%{\e[0;34m%}%n%{\e[0m%}%{\e[0m%} '\
$'%{\e[0;35m%}%~%{\e[0m%} $(git_super_status) $(vi_mode_prompt_info)\r\n%{\e[1;31m%}%B%#%b%{\e[0m%} '
#Cancel right prompt
RPROMPT=""

#vi-mode prompt indicator
MODE_INDICATOR="%{$fg_bold[green]%}NORMAL MODE%{$reset_color%}"

ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=blue'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=blue'

# Compilation flags
# export ARCHFLAGS="-arch x86_64"

# alias ohmyzsh="mate ~/.oh-my-zsh"
#
#
