# Path to your oh-my-zsh installation.
export ZSH="/home/aner/.oh-my-zsh"

# Uncomment the following line to disable auto-setting terminal title.
DISABLE_AUTO_TITLE="true"

#Path to FZF
export FZF_BASE=~/.fzf

plugins=(git-prompt vi-mode colored-man-pages fzf zsh-syntax-highlighting)

#Load up ZSH
source $ZSH/oh-my-zsh.sh

ZSH_THEME_GIT_PROMPT_BRANCH="%{$fg[blue]%}"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8
 
export EDITOR='vim'

#Edit command with VIM with Ctrl+e
autoload edit-command-line; zle -N edit-command-line
bindkey '^e' edit-command-line

#Setting PS1
PS1=$'%{\e[0m%}%{\e[0;34m%}%n%{\e[0m%}%{\e[0m%} '\
$'%{\e[0;35m%}%~%{\e[0m%} $(git_super_status) $(vi_mode_prompt_info)\r\n%{\e[1;31m%}%B%#%b%{\e[0m%} '

#Cancel right prompt
RPROMPT=""

#vi-mode prompt indicator
MODE_INDICATOR="%{$fg_bold[green]%}NORMAL MODE%{$reset_color%}"

#Change string highlighting to blue
ZSH_HIGHLIGHT_STYLES[single-quoted-argument]='fg=blue'
ZSH_HIGHLIGHT_STYLES[double-quoted-argument]='fg=blue'
